spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

# Mybatis
mybatis:
  mapper-locations: classpath*:**/xml/**.xml
  type-aliases-package: tech.maiquer.maiqucounseling

sa-token:
  token-name: satoken
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: false
